
spring:
  application:
    name: Baadni
  datasource:
    password: root
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/springtest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
